### ISSUE TITLE
Stored procedures

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/conta-digital#10]
Criar e justificar a escolha de stored procedures.

**Comment by ardnaile** [comment]
- [ ] procedimento para transação;
- [ ] obtenção de saldo;
- [ ] gerar extrato;
- [ ] bloquear conta;

**Comment by Rafael171022** [comment]
Criado 2 procedure 
uma para criar novo usuário e outra para avisar que a conta esta bloqueada

**Comment by Rafael171022** [comment]
Procedures criadas : Bloquear conta, desbloquear conta, criar novo usuário, criar cartão de debito
