### ISSUE TITLE
Atualizacao do README.md

### ISSUE THREAD

**Issue by jlsilva01** [ardnaile/conta-digital#13]
Favor atualizar o README.md do repo de voces. utilizando este repo - https://github.com/jlsilva01/projeto_final_bd2_satc_2023 - como base.

**Comment by ardnaile** [comment]
Será atualizado amanhã quando as demais tarefas tiverem sido concluídas.

**Comment by ardnaile** [comment]
Read.me atualizado conforme solicitado. Como foi feita a organização por pastas, mesmo fazendo novos commits dentro das pastas, o read.me estará com os caminhos corretos.
