### ISSUE TITLE
Scripts de criação do banco de dados

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/conta-digital#3]
- Para a documentação: 1 arquivo .sql por tabela
- SGDB SQL Server

**Comment by TheoGomide** [comment]
# 24/11

* Criada pasta Scripts-DDl na root do projeto
* Separado as tabelas do arquivo modelo-físico-conta-digital.sql localizado na root do projeto em seus respectivos arquivos .sql
* Adicionado os arquivos .sql a pasta Scripts-DDl
![Commit 2023-11-24 201457](https://github.com/ardnaile/conta-digital/assets/69534996/8029ce32-3dbb-4428-8fc9-d90c1edc0751)
