### ISSUE TITLE
População de tabelas

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/conta-digital#4]
- mínimo 10 itens principais

**Comment by TheoGomide** [comment]
# 24/11

* Criada pasta Scripts-DML na root do projeto
* Adicionado 10 itens para cada tabela da pasta Scripts-DDL
![commit2023-11-24 234100](https://github.com/ardnaile/conta-digital/assets/69534996/2ff98558-fc9b-4c29-9af0-3b2c4f0d1448)
![commit2 2023-11-24 234313](https://github.com/ardnaile/conta-digital/assets/69534996/604820ff-f0ea-4e89-9ed3-d2e783f896f9)
