### ISSUE TITLE
Perguntas de negócios

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/conta-digital#7]
- [x] Criar e responder 4 perguntas de negócio relacionadas ao projeto
- [x] Documentar no pdf
- [x] Documentar na apresentação

**Comment by WallaceB2** [comment]
Beleza, vou elaborar essas consultas. Acredito que vou criar mais algumas além dessas. Pois dessas 4 perguntas apenas a terceira vai resultar em uma consulta mais complexa, o restante são bem simples de fazer.

**Comment by WallaceB2** [comment]
Alterei algumas perguntas para as consultas ficarem mais interessantes, segue nova lista de perguntas:

- Quais foram os usuários que mais movimentaram suas contas no último ano?
- Quais usuários não têm transações registradas?
- Quais tipos de contas estão associados a cada usuário?
- Quais são os tipos de transações mais comuns nas contas digitais?

**Comment by WallaceB2** [comment]
Finalizei os tópicos dessa issue.
